### ISSUE TITLE
Support for well known folder

### ISSUE THREAD

**Issue by rasod** [ethanhuang13/knil#14]
Can’t seem to get app to load AASS file when stored in .well-known folder

/.well-known/apple-app-site-association

https://developer.apple.com/library/archive/qa/qa1919/_index.html

**Comment by ethanhuang13** [comment]
Did you specify the URL with https://domain/.well-known/apple-app-site-association or just https://domain ?

By default, Knil will grab AASA from root. Specify /.well-known by yourself if you need.

**Comment by rasod** [comment]
I tried entering the full domain it just removes the .well-known segment not sure what I’m doing wrong

**Comment by ethanhuang13** [comment]
May I ask what is your domain? Or send me though in-app feedback.

**Comment by ethanhuang13** [comment]
I've check the issue.
According to the [document](https://developer.apple.com/library/archive/qa/qa1919/_index.html), iOS will try to fetch from /.well-known/apple-app-site-association first, if failed, then fetch from /apple-app-site-assoication.

Knil's fetching order is reversed. And it should be fixed. 
Thanks for reporting the issue.

Meanwhile, you can first enter nothing and tap "I'm Felling Lucky", paste the URL, then tap "Go".

**Comment by ethanhuang13** [comment]
Fixed in v1.1.0. Close issue.
